version: 0.2
env:
  git-credential-helper: yes
phases:
#  pre_build:
#    commands:
#      - |
#        if [ -z "$(git diff --name-only HEAD HEAD~1 | grep 'infra/')" ]; then
#          echo "No Infra changes. Skipping build."
#          exit 0
#        else
#          echo "Infra changes detected. Running build."
#        fi

  install:
    runtime-versions:
      python: 3.12
    commands:
      - apt-get update
      - apt-get install -y unzip
      - curl -o terraform.zip -L https://releases.hashicorp.com/terraform/1.0.0/terraform_1.0.0_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - terraform --version

  build:
    commands:
      - |
        if [ -z "$(git diff --name-only HEAD HEAD~1 | grep 'infra/')" ]; then
          echo "No Infra changes. Skipping build."
          exit 0
        else
          echo "Infra changes detected. Running build."
        cd infra/terraform/deployments/development/awsentry-api
        echo "Running Terraform Init..."
        terraform init
        echo "Running Terraform Plan..."
        terraform plan
        echo "Running Terraform Apply..."
        terraform apply -auto-approve
        fi
#      - cd infra/terraform/deployments/development/awsentry-api
#      - echo "Running Terraform Init..."
#      - terraform init
#      - echo "Running Terraform Plan..."
#      - terraform plan
#      - echo "Running Terraform Apply..."
#      - terraform apply -auto-approve
# added comment
artifacts:
  files:
    - '**/*'
