version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - apt-get update
      - apt-get install -y unzip
      - curl -o terraform.zip -L https://releases.hashicorp.com/terraform/1.0.0/terraform_1.0.0_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - terraform --version

  build:
    commands:
      - cd infra/terraform/deployments/development/api-gateway
      - echo "Running Terraform Init..."
      - terraform init
      - echo "Running Terraform Plan..."
      - terraform plan
      - echo "Running Terraform Apply..."
      - terraform apply -auto-approve

      - cd ../../user-management
      - echo "Running Terraform Init..."
      - terraform init
      - echo "Running Terraform Plan..."
      - terraform plan
      - echo "Running Terraform Apply..."
      - terraform apply -auto-approve

artifacts:
  files:
    - '**/*'
