version: 0.2

phases:
  install:
    commands:
      - echo "Installing necessary dependencies"

  pre_build:
    commands:
      - echo "pre_build"

  build:
    commands:
      - echo "Running build script"
      - cd src/python
      - chmod +x build-all.sh
      - pwd
      - ./build-all.sh $ACCOUNT_ID

  post_build:
    commands:
      - echo "Post-build steps"

artifacts:
  files:
    - '**/*'
# added comment
cache:
  paths:
    - 'path/to/cache/directory'
