version: 0.2

phases:
  pre_build:
    commands:
      - |
        if [ -z "$(git diff --name-only HEAD HEAD~1 | grep 'src/')" ]; then
          echo "No Python changes. Skipping build."
          exit 0
        else
          echo "Python changes detected. Running build."
        fi
  install:
    commands:
      - echo "Installing necessary dependencies"
  build:
    commands:
      - echo "Running build script"
      - cd src/python
      - chmod +x build-all.sh
      - pwd
      - ./build-all.sh $ACCOUNT_ID

  post_build:
    commands:
      - echo "Post-build steps"

artifacts:
  files:
    - '**/*'
# added
cache:
  paths:
    - 'path/to/cache/directory'
